### ISSUE TITLE
Attenuator.md

### ISSUE THREAD

**Issue by Beelzebot42** [gpstar81/haslab-proton-pack#195]
In the attenuator section I think there is a typo. You show that a 470k Ω resistor for the attenuator lights signal wire. I think that should be just 470 Ω? 

470k Ω the lights wouldn't work. Looking at Neopixel support page it looked like the error was the "k" rating.

-RP

LED'S |   | Component | Nano Pin
-- | -- | -- | --
Red | → | 100uf | 5V
Blue | → | 470k Ω | Pin D9
Black | → | 100uf | GND

**Comment by DustinGrau** [comment]
Yes, this was a typo and has been fixed in some upcoming changes.
